### ISSUE TITLE
How to enable this extension?

### ISSUE THREAD

**Issue by chorig9** [jedrus2000/mopidy-audioteka#3]
Hi,

Is there any extra step (besides installing and adding a config) necessary to use this extension? I don't see audioteka in the web client (iris) after restarting mopidy service. Also, I don't see any audioteka related logs in `systemctl status mopidy` output.

Thanks

**Comment by jedrus2000** [comment]
Hi !

> 
> Is there any extra step (besides installing and adding a config) necessary to use this extension? 

No. My entry in config looks like :
![image](https://user-images.githubusercontent.com/22714418/82148373-0d895400-9854-11ea-9303-e8b666540f8d.png)

What Mopidy server version are you using ? I'am still with 2.2.2 version.

> I don't see audioteka in the web client (iris) after restarting mopidy service. Also, I don't see any audioteka related logs in `systemctl status mopidy` output.
> 

Mopidy by default is not so verbose, so maybe try to switch into DEBUG level mode ?

I.e in mopidy config : 
![image](https://user-images.githubusercontent.com/22714418/82148599-06167a80-9855-11ea-8e3d-afafd713248a.png)

Then my `logging.conf`
```
[loggers]
keys = root

[handlers]
keys = fileHandler

[formatters]
keys = simpleFormatter

[logger_root]
handlers = fileHandler

[handler_fileHandler]
class = FileHandler
formatter = simpleFormatter
level = DEBUG
args = ('/var/log/mopidy/mopidy.log',)

[formatter_simpleFormatter]
format = %(asctime)s %(levelname)s [%(process)d:%(threadName)s] %(name)s: %(message)s
datefmt =

```

**Comment by chorig9** [comment]
Thanks for the tips!

I'm running mopidy 3.0.2 and I figured out why audioteka backend didn't start up:

1. there was some syntax error with exceptions:

```
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.7/dist-packages/Mopidy_Audioteka-0.1.5-py3.7.egg/mopidy_audioteka/library.py", line 103
    except AudiotekaError, e:
                         ^
SyntaxError: invalid syntax
```
I 'fixed' that: https://github.com/jedrus2000/mopidy-audioteka/compare/master...chorig9:master.

2. There is a problem with using: https://docs.mopidy.com/en/release-2.2/api/models/#mopidy.models.Album.images (deprecated in 2.2.2 and removed in 3.0.3). I tried to use `LibraryController.get_images` but didn't manage to make it work yet. Anyway, this just a minor issue, I can live without images.

There is one more problem when I try to play a track (it just hangs):

```
DEBUG    [AudiotekaBackend-3] mopidy_audioteka.playback Playback. Waiting for first data chunk...
maj 17 18:21:14 igor-VirtualBox mopidy[8041]: Exception in thread Thread-20:
maj 17 18:21:14 igor-VirtualBox mopidy[8041]: Traceback (most recent call last):
maj 17 18:21:14 igor-VirtualBox mopidy[8041]:   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
maj 17 18:21:14 igor-VirtualBox mopidy[8041]:     self.run()
maj 17 18:21:14 igor-VirtualBox mopidy[8041]:   File "/usr/local/lib/python3.7/dist-packages/Mopidy_Audioteka-0.1.5-py3.7.egg/mopidy_audioteka/playback.py", line 55, in run
maj 17 18:21:14 igor-VirtualBox mopidy[8041]:     self._target(*self._args)
maj 17 18:21:14 igor-VirtualBox mopidy[8041]: TypeError: 'NoneType' object is not callable
```

**Comment by chorig9** [comment]
Ok, I fixed the playback problem (it was just a matter of self._target being overwritten by super ctor).
However, now I got unauthorized access to audioteka. More specifically: the 'chunks' which are downloaded and saved in '/var/cache/mopdy/track_no' are just HTML files with:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
...
```

I can browse the shelf without any problems (I see all my audiobooks), the problem is only for downloading the files.

**Comment by jedrus2000** [comment]
Maybe there is mix of issues related to new version of Mopidy, and the way Audioteka service works.
Take look at discussion starting here : https://discourse.mopidy.com/t/audiobook-plugin/1264/18?u=jedrus2000

Main issue is that Mopidy is not supporting all functionality found in GStreamer, needed for Audioteka (Digest authorization) and my current solution is just workaround, far from perfect but it worked for 99% of my audio books collection. So I left until someone will complain :smile: 

BTW, does this https://github.com/jedrus2000/audtekapi cmd line tool works for you ? I mean can you download any of your audio books ? 

I will try to look into code in next weeks to fix things, but any contribution are welcome !

**Comment by chorig9** [comment]
So, It looks like the cause was much simpler 😄
Everything works fine after https://github.com/jedrus2000/audtekapi/pull/1

Thanks!

**Comment by chorig9** [comment]
I had some time and tried to fix the problem with album images. If you're interested I've made a PR with all changes required to run mopidy-audioteka on mopidy python3 with mopidy 3.x
